version: "3"

services:

  app: 
    build: ./
    restart: always
    env_file: 
      - .env
    ports:
      - 3000:3000
    command: npm run start
    container_name: app
    env_file: 
      - .env
    networks:
      - app-network

  job_consumer: 
    build: ./
    restart: always
    env_file: 
      - .env
    command: npm run job
    container_name: job_consumer_app
    env_file: 
      - .env
    networks:
      - app-network

  message_broker:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 15672:15672
      networks:
        - app-network
  
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./datas:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=metrics_api_gateway
    ports: 
     - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


 